version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: acme-csr-app
    container_name: acme-csr-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8008:8000"
    depends_on:
      - db
    networks:
      - csr-network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=acme_csr
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret

  db:
    image: postgres:15
    container_name: acme-csr-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: acme_csr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - csr-network

volumes:
  pgdata:

networks:
  csr-network:
    driver: bridge
